### PR TITLE
Create a Go project able to build

### PR DESCRIPTION
**Pull request by houshengbo**

### CODE REVIEW

**Comment by houshengbo** [comment]
@csantanapr I moved the code out of bluewhisk into this repo, and set up the build process.
This repo is able to build either by go build command or the gradlew command.

**Comment by csantanapr** [comment]
Vincent can we retain the original author commits? Or you ok if I rewrite the commit author?

**Comment by csantanapr** [comment]
Maybe it could be 2 commits one for the original code and another from you on any changes to make work in this repo

**Comment by houshengbo** [comment]
@csantanapr You can rewrite the author.

**Pull request closed without merging**
